{% set version = "1.0.0" %}
{% set sha256 = "7928a36042f87b2aecaf37c4b3979bc49c19d933eeb9c4977be752b6f6b95dca" %}

package:
  name: fsfe-reuse
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/fsfe-reuse/fsfe-reuse-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  entry_points:
    - reuse = reuse._main:main
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - binaryornot
    - boolean.py
    - jinja2
    - license-expression
    - python >=3.6
    - python-debian
    - requests

test:
  imports:
    - reuse
  commands:
    - reuse --help

about:
  home: https://reuse.software/
  license: GPL-3.0-or-later AND Apache-2.0 AND CC0-1.0 AND CC-BY-SA-4.0
  license_file:
    - LICENSES/GPL-3.0-or-later.txt
    - LICENSES/Apache-2.0.txt
    - LICENSES/CC0-1.0.txt
    - LICENSES/CC-BY-SA-4.0.txt
  summary: reuse is a tool for compliance with the REUSE recommendations.
  doc_url: https://reuse.readthedocs.io/
  dev_url: https://github.com/fsfe/reuse-tool

extra:
  recipe-maintainers:
    - mbargull
