{% set version = "1.0.0" %}

package:
  name: fsfe-reuse
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/fsfe-reuse/fsfe-reuse-0.6.0.tar.gz
  sha256: 2667325ce87a1469966e9e2fb65c0cdd6fe11cba6a6443327661efc382454144

build:
  number: 0
  noarch: generic

requirements:
  run:
    - reuse

test:
  commands:
    - reuse --help


about:
  home: https://reuse.software/
  license: GPL-3.0-or-later AND Apache-2.0 AND CC0-1.0 AND CC-BY-SA-4.0
  license_file:
    - LICENSES/GPL-3.0-or-later.txt
    - LICENSES/Apache-2.0.txt
    - LICENSES/CC0-1.0.txt
    - LICENSES/CC-BY-SA-4.0.txt
  summary: fsfe-reuse is an alias for reuse.
  description: |
    As of version 0.7.0, [reuse](https://pypi.org/project/reuse/) is
    used instead of fsfe-reuse.

    If you still depend on fsfe-reuse, then you will automatically get
    the latest version of reuse. This dummy package depends on reuse.

    If you depend on a specific older version of fsfe-reuse, then you
    will continue to get that version.
  doc_url: https://reuse.readthedocs.io/
  dev_url: https://github.com/fsfe/reuse-tool

extra:
  recipe-maintainers:
    - mbargull
